name: Integration

on:
  push:
  workflow_call:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: cd into /src
      run: cd src && pwd
        
    - name: Build
      run: go build .
      
    - name: Test
      run: go test .
      
    - name: Coverage
      run: ../scripts/coverage.sh
